# Generated by Django 5.0.3 on 2024-03-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=250),
        ),
    ]
