# Generated by Django 5.0.2 on 2024-02-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(
                default="uploads/default.jpg", upload_to="uploads/%Y/%m/%d"
            ),
        ),
    ]
