# Generated by Django 5.0.3 on 2024-03-16 16:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_body",
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="blog",
            name="short_description",
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
